# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=0, max_length=60),
        ),
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
